"""
Transcript Models.

Models for storing and managing call transcripts,
including integration with the Ingest API for document storage.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field

from .call_state import Speaker


class TranscriptSegment(BaseModel):
    """
    A segment of transcribed audio.
    
    Represents a continuous segment of speech from a single speaker.
    """

    id: UUID = Field(default_factory=uuid4)
    start_time_ms: int  # Offset from call start
    end_time_ms: int
    speaker: Speaker
    text: str
    confidence: float = 1.0
    
    # Audio metadata
    language: str = "en"
    is_final: bool = True  # False for interim/partial results
    
    # Additional annotations
    sentiment: Optional[str] = None  # positive, negative, neutral
    keywords: List[str] = Field(default_factory=list)
    entities: List[Dict[str, str]] = Field(default_factory=list)

    @property
    def duration_ms(self) -> int:
        """Get segment duration in milliseconds."""
        return self.end_time_ms - self.start_time_ms


class Transcript(BaseModel):
    """
    Complete call transcript.
    
    Contains all segments from a call, with metadata for storage
    and search integration.
    """

    id: UUID = Field(default_factory=uuid4)
    call_session_id: UUID
    user_id: str
    
    # Call metadata
    phone_number: str
    target_name: Optional[str] = None
    call_direction: str = "outbound"  # outbound, inbound
    
    # Timing
    call_started_at: datetime
    call_ended_at: Optional[datetime] = None
    call_duration_seconds: int = 0
    
    # Transcript content
    segments: List[TranscriptSegment] = Field(default_factory=list)
    
    # Summary (generated by AI)
    summary: Optional[str] = None
    topics: List[str] = Field(default_factory=list)
    action_items: List[str] = Field(default_factory=list)
    
    # Storage integration
    saved_to_library: bool = False
    document_id: Optional[str] = None  # ID in Ingest API
    library_id: Optional[str] = None
    
    # Metadata
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = Field(default_factory=dict)

    def add_segment(
        self,
        speaker: Speaker,
        text: str,
        start_time_ms: int,
        end_time_ms: int,
        confidence: float = 1.0,
    ) -> TranscriptSegment:
        """Add a new segment to the transcript."""
        segment = TranscriptSegment(
            speaker=speaker,
            text=text,
            start_time_ms=start_time_ms,
            end_time_ms=end_time_ms,
            confidence=confidence,
        )
        self.segments.append(segment)
        self.updated_at = datetime.utcnow()
        return segment

    @property
    def full_text(self) -> str:
        """Get the complete transcript as plain text."""
        lines = []
        for segment in sorted(self.segments, key=lambda s: s.start_time_ms):
            speaker_label = segment.speaker.value.upper()
            lines.append(f"[{speaker_label}]: {segment.text}")
        return "\n".join(lines)

    @property
    def full_text_with_timestamps(self) -> str:
        """Get the complete transcript with timestamps."""
        lines = []
        for segment in sorted(self.segments, key=lambda s: s.start_time_ms):
            speaker_label = segment.speaker.value.upper()
            time_str = self._format_time(segment.start_time_ms)
            lines.append(f"[{time_str}] [{speaker_label}]: {segment.text}")
        return "\n".join(lines)

    @staticmethod
    def _format_time(ms: int) -> str:
        """Format milliseconds as MM:SS."""
        total_seconds = ms // 1000
        minutes = total_seconds // 60
        seconds = total_seconds % 60
        return f"{minutes:02d}:{seconds:02d}"

    def to_markdown(self) -> str:
        """Convert transcript to Markdown format for document storage."""
        parts = [
            f"# Call Transcript",
            f"",
            f"**Phone Number:** {self.phone_number}",
        ]
        
        if self.target_name:
            parts.append(f"**Target:** {self.target_name}")
        
        parts.extend([
            f"**Date:** {self.call_started_at.strftime('%Y-%m-%d %H:%M:%S')}",
            f"**Duration:** {self.call_duration_seconds // 60}m {self.call_duration_seconds % 60}s",
            f"**Direction:** {self.call_direction}",
            f"",
        ])
        
        if self.summary:
            parts.extend([
                f"## Summary",
                f"",
                self.summary,
                f"",
            ])
        
        if self.topics:
            parts.extend([
                f"## Topics",
                f"",
            ])
            for topic in self.topics:
                parts.append(f"- {topic}")
            parts.append("")
        
        if self.action_items:
            parts.extend([
                f"## Action Items",
                f"",
            ])
            for item in self.action_items:
                parts.append(f"- [ ] {item}")
            parts.append("")
        
        parts.extend([
            f"## Transcript",
            f"",
            "```",
            self.full_text_with_timestamps,
            "```",
        ])
        
        return "\n".join(parts)
